### ISSUE TITLE
RMTP Broadcast

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [eyeson-team/eyeson-ruby#2]
Hi,

I just wanted to ask if it's possible to create an RTMP broadcast?
Would it be possible to implement it in your system?

Thanks!

**Comment by unused** [comment]
Ahoi, we discussed this topic several times but did not yet provide a convenient way through API to do so, but I'm happy to bring this topic back to table. Would you mind leaving a note what the main purpose of your project is and to name the task you want to handle using eyeson? Thanks in advance!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Last week we were talking with Peter about streaming the video content to more than 1000 people at the same time, and the suggestion was that we use Eyeson only for the content generation and broadcast the final stream somewhere else via RTMP.. 

Do you think you can implement this RTMP streaming output soon?
Our current target is to probably stream to Vimeo for the final transmittion to the users.

Thanks!

**Comment by unused** [comment]
We will try to update the API asap, I'll leave a note when we published the changes.

**Comment by unused** [comment]
We have successfully tested the RTMP endpoints for our services, and proceed to the final tests soon. I've added Vimeo to the test candidates for QA and will let you know as soon as we've released a new version to production as well as on any updates for the documentation. Additionally we might add the RTMP settings to our provided web GUI, yet it is not on the roadmap yet. Best wishes!

**Comment by unused** [comment]
Our services are updated with some improvements on RTMP streaming, we've successfully tested on different platforms like YouTube, Vimeo, Twitch and others in the last days. The following script provides you with some example usage, you only need to provide your eyeson access key for an active meeting and the Vimeo Streaming Key.

```
#!/bin/sh

# Vimeo

# echo "stream_url=rtmp://rtmp-global.cloud.vimeo.com/live/${2}\n"
# echo "https://api.eyeson.team/rooms/${1}/broadcasts\n"
curl -vv -X POST \
  -d "platform=generic" \
  -d "stream_url=rtmp://rtmp-global.cloud.vimeo.com/live/${2}" \
  "https://api.eyeson.team/rooms/${1}/broadcasts"

# # stop a broadcast
# curl -v -X DELETE "https://api.eyeson.team/rooms/${1}/broadcasts/generic"
```

Good luck and stay safe!
