### ISSUE TITLE
insert image to video

### ISSUE THREAD

**Issue by VictorTao1998** [eyeson-team/eyeson-ruby#4]
Hi dev team,
I was trying your eyeson Ruby Quickstart Tutorial demo (the one that uses sinatra and heroku) and I am new to ruby language. I would like to insert image to video cell, but I don't know when should I use Eyeson::Layer.create() function. I have tried to append this function after Eyeson::Room.join and store the access_key as global variable, but nothing happened. Thank you for any help.

**Comment by unused** [comment]
Hi Victor, the quick start demo is a very easy one, to set an image on start you might need to wait for the room to be ready which requires background workers or a trigger on webhook receive. However to test the feature I'd recommend to use curl and [the snippet provided in the API documentation section](https://eyeson-team.github.io/api/api-reference/#content-integration-aka-layers):

```sh
$ curl -X POST \
  -d "url=https://eyeson-team.github.io/api/images/eyeson-overlay.png" \
  "https://api.eyeson.team/rooms/${ACCESS_KEY}/layers"
```

**Comment by VictorTao1998** [comment]
Thank you, I have another question, when I try to broadcast the meeting using curl, there is an error saying that "Broadcast feature is not available for this room".

**Comment by unused** [comment]
That does not sound as if you are receiving this message from our API services. Can you try to use the platform identifier "generic" (which is also ok to use with youtube or facebook) and double-check you set the proper RTMP values.
